[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dreamdata"
version = "0.0.1"
requires-python = ">=3.9"
dependencies = [
    "ocflindex @ git+https://github.com/srerickson/ocfl-index-py@main",
    "stream_unzip ~= 0.0.85"
]